### ISSUE TITLE
Add logging of screen power/lock state

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-watcher-afk#3]
### Windows
- Power: http://stackoverflow.com/questions/203355/is-there-any-way-to-detect-the-monitor-state-in-windows-on-or-off
- Lock: http://stackoverflow.com/questions/768314/detect-if-desktop-is-locked
### Linux
- Lock: Look for dbus events (broadcast by Ubuntu's Unity for example) and running processes (slock, xscreensaver)
- Power: http://stackoverflow.com/questions/3433203/how-to-determine-if-lcd-monitor-is-turned-on-from-linux-command-line

Best would be if this functionality was extracted to a library, which could poll/listen for state change for multiple environments. The process-monitor should probably be outsourced to a stable lib, or abstracted away in a lib.

**Comment by johan-bjareholt** [comment]
Isn't this kind of fixed? We notice when the watcher is not running for a prolonged amount of time and the clock skips, so that should be sufficient? Or do you actually want to send a event with a "suspend" label or something?

**Comment by ErikBjare** [comment]
Kind of fixed yeah, at least the necessary parts. Closing.

**Comment by exscape** [comment]
Hmm, I think this is still an issue 6 years later.  
If I lock my computer at 9:00:00 and unlock it at 9:02:55 that time counts as non-AFK since less than 180 seconds passed. IMO all time the screen is locked or turned off (or a screensaver is running) should count as AFK.

Despite locking twice in the last 10 minutes, I've been non-AFK for over 20.
