### ISSUE TITLE
Incorrect AFK detection

### ISSUE THREAD

**Issue by dufferzafar** [ActivityWatch/aw-watcher-afk#33]
Was watching a movie today, using MPV (green is mpv, orange is firefox): 

![image](https://user-images.githubusercontent.com/1449512/37909845-a9a495be-3129-11e8-8536-ff7079e5a603.png)

The AFK region towards the end is where I had mpv maximized (playing the movie.) 
Furthermore, I was pressing a few keys every now and then too - to raise volume or seek ahead etc.

Why could it be detecting that I was away?

Also, what happens when I'm marked AFK? Does the window watcher stop recording active windows? or are those events recorded but just not displayed on the UI?

**Comment by dufferzafar** [comment]
> Also, what happens when I'm marked AFK? Does the window watcher stop recording active windows? or are those events recorded but just not displayed on the UI?

I think I've found the answer to that question. The sunburst is showing the data correctly so it is being stored in the DB but is not being displayed in the timeline or the Top Applications / Top Window Titles view correctly.

![2018-03-26_19-33-26](https://user-images.githubusercontent.com/1449512/37911171-f1782e98-312c-11e8-83db-e875936afa1f.png)

**Comment by johan-bjareholt** [comment]
I think I have a guess of what could go wrong here.

As you can see in the sunburst view the data which is collected is correct, however when the transformation in aw-core which does the aggregation for the timeline intersects the window event with the non-afk events. Since this window event is the same across multiple non-afk events, it only intersects with the first one available and skips the rest.

I am not 100% certain though, will take a further look at the transformation and querying code in aw-core later.

**Comment by johan-bjareholt** [comment]
Here's the issue, it always assumes that it should check the next event instead of incrementing to the next event with the lowest end period. Should only need another if/else statement to the incrementing.

https://github.com/ActivityWatch/aw-core/blob/bc13f183ed002b21084230314c71663e6af16072/aw_transform/filter_period_intersect.py#L54

Thanks for finding this issue!

**Comment by johan-bjareholt** [comment]
Pull latest aw-core master, restart aw-server and test if it works. Hopefully it should!

https://github.com/ActivityWatch/aw-core/pull/51
